Make the deploy action inputless

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,14 +1,8 @@
 name: Deploy
 on:
   workflow_call:
-    inputs:
-      image-and-tag:
-        required: true
-        type: string
-      container-app-name:
-        required: true
-        type: string
-jobs:  
+
+jobs:
   build-and-push:
     runs-on: ubuntu-latest
     permissions:
@@ -18,13 +12,47 @@ jobs:
       - name: Check Out Repo
         uses: actions/checkout@v2
 
+      - name: Set repo name
+        id: repo
+        run: |
+         echo "::set-output name=repo::$(echo ${{ github.repository }} | cut -d'/' -f2)"
+
+      - name: Set container name
+        id: container
+        run: |
+          if [[ "${{ github.workflow }}" == "Land" ]]; then
+            echo "::set-output name=container::$(echo ${{ steps.repo.outputs.repo }} | cut -d'/' -f2 | tr '.' '-')-land"
+          else
+            echo "::set-output name=container::$(echo ${{ steps.repo.outputs.repo }} | cut -d'/' -f2 | tr '.' '-')"
+          fi
+
+      - name: Set image tag
+        id: tag
+        run: |
+          if [[ "${{ github.workflow  }}" == "Land" ]]; then
+            echo "::set-output name=tag:land"
+          elif [[ "${{ github.workflow }}" == "Deploy" ]]; then
+            echo "::set-output name=tag:latest"
+          else
+            echo "Invalid deployTo value"
+            exit 1
+          fi
+
       - name: Install Dependencies
         run: npm ci
 
       - name: Build
         run: npm run build
 
+      - name: Print Names
+        run: |
+          echo "Repo: ${{ steps.repo.outputs.repo }}"
+          echo "Container: ${{ steps.container.outputs.container }}"
+          echo "Tag: ${{ steps.tag.outputs.tag }}"  
+
       - name: Log in to Docker Hub
+        env:
+          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
         uses: docker/login-action@v1
         with:
           username: canmingir
@@ -34,7 +62,7 @@ jobs:
         uses: docker/build-push-action@v2
         with:
           push: true
-          tags: canmingir/${{ inputs.image-and-tag }}
+          tags: canmingir/${{ steps.repo.outputs.repo }}:${{ steps.tag.outputs.tag }}
           context: .
 
       - name: Azure Login
@@ -47,6 +75,7 @@ jobs:
           registryUsername: canmingir
           registryUrl: registry.hub.docker.com
           registryPassword: ${{ secrets.DOCKER_ACCESS_TOKEN }}
-          containerAppName: ${{ inputs.container-app-name }}
+          containerAppName: ${{ steps.container.outputs.container }}
           resourceGroup: NucGroup
-          imageToDeploy: registry.hub.docker.com/canmingir/${{ inputs.image-and-tag }}
+          imageToDeploy: registry.hub.docker.com/canmingir/${{ steps.repo.outputs.repo }}:${{ steps.tag.outputs.tag }}
+
